name = "GA"
uuid = "8f5180b1-7e39-42c0-bd0b-bd175cde0f3e"
authors = ["BPalhano <igor.palhano@alu.ufc.br>"]
version = "0.1.0"

[deps]
Evolutionary = "86b6b26d-c046-49b6-aa0b-5f0f74682bd6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
